### PR TITLE
Add astrology

### PR DESCRIPTION
**Pull request by kspalmer**
This is the pull request to add astrology to the Fortune Teller.  All Javadoc comments have been added.  Please review and let's plan to merge this after we've received comments in accordance with our Coding Standards and Best Practices.  Looking forward to your comments.

### CODE REVIEW

**Review by hellokaty37 — APPROVED** [review]
Everything looks good to me.

**Review by acfortier — APPROVED** [review]
Looks great!

**Comment by kspalmer** [comment]
Thanks, Kathryn and Alex.

**Comment by kspalmer** [comment]
can this be merged since we have had two add'l team members comment?  :)

**Comment by acfortier** [comment]
Yes, let's go ahead and merge!

**Pull request merged**
